import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import localFont from 'next/font/local';
import './globals.css';
import { Providers } from './providers';
import { AuthProvider } from '@/components/context/AuthProvider';
import { Toaster } from '@/components/ui/sonner';
import { SidebarLayout } from '@/components/sidebar-layout';
import { NavigationLoadingOverlay } from '@/components/NavigationLoadingOverlay';
import { EventWidgetProvider } from '@/components/context/EventWidgetProvider';
import EventWidget from '@/components/EventWidget';
import WidgetTrigger from '@/components/WidgetTrigger';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

const centuryGothic = localFont({
  src: [
    {
      path: '../public/fonts/centurygothic.ttf',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../public/fonts/centurygothic_bold.ttf',
      weight: '700',
      style: 'normal',
    },
  ],
  variable: '--font-century-gothic',
});

export const metadata: Metadata = {
  title: 'drAIn',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${centuryGothic.variable} antialiased`}
      >
        <AuthProvider>
          <Providers>
            <EventWidgetProvider>
              <SidebarLayout>
                {/* <WidgetTrigger /> */}
                {children}
              </SidebarLayout>
              <NavigationLoadingOverlay />
              <Toaster position="top-center" />
              <EventWidget />
            </EventWidgetProvider>
          </Providers>
        </AuthProvider>
      </body>
    </html>
  );
}
