"use client";

import { Skeleton } from "@/components/ui/skeleton";
import {
  getZoneColorByCount,
  loadMandaueGeoJSON,
  type GeoJSONFeatureCollection,
} from "@/lib/dashboard/geojson";
import type { ZoneIssueData } from "@/lib/dashboard/queries";
import { AlertCircle } from "lucide-react";
import { useEffect, useRef, useState } from "react";
import mapboxgl from "mapbox-gl";
import "mapbox-gl/dist/mapbox-gl.css";

const MAPBOX_TOKEN = process.env.NEXT_PUBLIC_MAPBOX_ACCESS_TOKEN;

interface ZoneMapProps {
  data: ZoneIssueData[];
  loading?: boolean;
}

export default function ZoneMap({ data, loading = false }: ZoneMapProps) {
  const mapContainer = useRef<HTMLDivElement>(null);
  const map = useRef<mapboxgl.Map | null>(null);
  const [mapError, setMapError] = useState<string | null>(null);
  const [geoJsonData, setGeoJsonData] =
    useState<GeoJSONFeatureCollection | null>(null);
  const [selectedZone, setSelectedZone] = useState<string | null>(null);

  // Load GeoJSON on mount
  useEffect(() => {
    const loadGeoJson = async () => {
      const data = await loadMandaueGeoJSON();
      setGeoJsonData(data);
    };
    loadGeoJson();
  }, []);

  // Initialize map
  useEffect(() => {
    if (!mapContainer.current || !MAPBOX_TOKEN) {
      if (!MAPBOX_TOKEN) {
        setMapError("Mapbox token not configured");
      }
      return;
    }

    if (!geoJsonData) return;

    try {
      mapboxgl.accessToken = MAPBOX_TOKEN;

      map.current = new mapboxgl.Map({
        container: mapContainer.current,
        style: "mapbox://styles/mapbox/light-v11",
        center: [123.93, 10.35],
        zoom: 11.5,
        pitch: 0,
        scrollZoom: false,
        dragPan: true,
        dragRotate: false,
        doubleClickZoom: false,
        touchZoomRotate: false,
      });

      map.current.on("load", () => {
        if (!map.current) return;

        // Add GeoJSON source
        map.current.addSource("barangay-source", {
          type: "geojson",
          data: geoJsonData as any,
          generateId: true,
        });

        // Add fill layer with soft gradient heatmap effect
        map.current.addLayer({
          id: "barangay-fill",
          type: "fill",
          source: "barangay-source",
          paint: {
            "fill-color": [
              "interpolate",
              ["linear"],
              ["coalesce", ["feature-state", "issueCount"], 0],
              0,
              "rgba(255, 255, 255, 0)",
              2,
              "rgba(219, 234, 254, 0.5)",
              5,
              "rgba(191, 219, 254, 0.6)",
              10,
              "rgba(96, 165, 250, 0.7)",
              15,
              "rgba(249, 115, 22, 0.75)",
              20,
              "rgba(220, 38, 38, 0.8)",
            ],
            "fill-opacity": [
              "interpolate",
              ["linear"],
              ["coalesce", ["feature-state", "issueCount"], 0],
              0,
              0.1,
              5,
              0.4,
              10,
              0.6,
              15,
              0.7,
              20,
              0.8,
            ],
          },
        });

        // Add thin outline layer
        map.current.addLayer({
          id: "barangay-outline",
          type: "line",
          source: "barangay-source",
          paint: {
            "line-color": "rgba(100, 100, 100, 0.4)",
            "line-width": 1,
            "line-opacity": 0.5,
          },
        });

        // Update feature state with issue counts
        if (geoJsonData.features) {
          geoJsonData.features.forEach((feature, index) => {
            const barangayName = feature.properties?.name;
            const zoneData = data.find(
              (z) => z.zone.toLowerCase() === barangayName?.toLowerCase()
            );
            const issueCount = zoneData?.count || 0;

            // Use index as ID (generated by Mapbox due to generateId: true)
            map.current?.setFeatureState(
              { source: "barangay-source", id: index },
              { issueCount }
            );
          });
        }
      });
    } catch (error) {
      console.error("Map error:", error);
      setMapError("Failed to initialize map");
    }

    return () => {
      map.current?.remove();
    };
  }, [geoJsonData, data, selectedZone]);

  // Loading state
  if (loading) {
    return (
      <div className="bg-white rounded-lg border border-[#ced1cd] p-6">
        <h3 className="text-lg font-semibold mb-4">
          Issues Per Zone (Barangay Breakdown)
        </h3>
        <div className="grid grid-cols-1 md:grid-cols-3 gap-6 items-stretch">
          <div className="md:col-span-2">
            <Skeleton className="h-[28rem] md:h-[36rem] w-full rounded-lg" />
          </div>
          <div className="space-y-3 h-[28rem] md:h-[36rem]">
            <Skeleton className="h-8 w-1/2" />
            <Skeleton className="h-6 w-full" />
            <Skeleton className="h-6 w-full" />
            <Skeleton className="h-6 w-full" />
          </div>
        </div>
      </div>
    );
  }

  if (!data || data.length === 0) {
    return (
      <div className="bg-white rounded-lg border border-[#ced1cd] p-6">
        <h3 className="text-lg font-semibold mb-4">
          Issues Per Zone (Barangay Breakdown)
        </h3>
        <div className="flex items-center justify-center h-48 text-gray-500">
          <p>No zone data available</p>
        </div>
      </div>
    );
  }

  // Sort by count descending
  const sortedData = [...data].sort((a, b) => b.count - a.count);
  const totalIssues = sortedData.reduce((sum, z) => sum + z.count, 0) || 0;

  return (
    <div className="bg-white rounded-lg border border-[#ced1cd] p-6">
      <h3 className="text-lg font-semibold mb-4">
        Issues Per Zone (Barangay Breakdown)
      </h3>

      <div className="grid grid-cols-1 md:grid-cols-3 gap-6 items-stretch">
        {/* Map: left 2/3 */}
        <div className="md:col-span-2">
          {mapError ? (
              <div className="bg-red-50 border border-red-200 rounded-lg h-[28rem] md:h-[36rem] flex items-center justify-center">
              <div className="text-center">
                <AlertCircle className="w-12 h-12 text-red-600 mx-auto mb-2" />
                <p className="text-red-800 font-medium">{mapError}</p>
                <p className="text-sm text-red-600 mt-1">
                  Please configure Mapbox token to enable map visualization
                </p>
              </div>
            </div>
          ) : (
              <div
                ref={mapContainer}
                className="rounded-lg h-[28rem] md:h-[36rem] border border-gray-300 overflow-hidden"
              />
          )}
        </div>

        {/* Top zones: right 1/3 */}
        <aside className="space-y-4 h-[28rem] md:h-[36rem] flex flex-col">
          <div className="p-3 rounded-md bg-gray-50 border">
            <p className="text-sm text-gray-600">Total Issues</p>
            <p className="text-2xl font-bold">{totalIssues}</p>
          </div>

          <div className="p-3 rounded-md bg-gray-50 border overflow-auto h-full">
            <h4 className="font-semibold text-gray-900 mb-3">Top Zones</h4>
            <ul className="space-y-2">
              {sortedData.slice(0, 12).map((zone) => {
                const { bgColor, color } = getZoneColorByCount(zone.count);
                const isSelected = zone.zone === selectedZone;
                return (
                  <li key={zone.zone}>
                    <button
                      onClick={() =>
                        setSelectedZone(zone.zone === selectedZone ? null : zone.zone)
                      }
                      className={`w-full flex items-center justify-between gap-3 p-2 rounded-md hover:bg-gray-100 transition-colors text-left ${
                        isSelected ? "ring-2 ring-offset-2 ring-blue-500" : ""
                      }`}
                    >
                      <div className="flex items-center gap-3">
                        <span className={`inline-block w-3 h-3 rounded-full ${bgColor}`} />
                        <span className="text-sm font-medium truncate">{zone.zone}</span>
                      </div>
                      <div className="text-right">
                        <div className={`text-lg font-semibold ${color}`}>{zone.count}</div>
                        <div className="text-xs text-gray-500">{totalIssues ? `${((zone.count / totalIssues) * 100).toFixed(0)}%` : "0%"}</div>
                      </div>
                    </button>
                  </li>
                );
              })}
            </ul>
          </div>
        </aside>
      </div>
    </div>
  );
}
