'use client';

import { Skeleton } from '@/components/ui/skeleton';
import {
  getZoneColorByCount,
  loadMandaueGeoJSON,
  type GeoJSONFeatureCollection,
} from '@/lib/dashboard/geojson';
import type { ZoneIssueData } from '@/lib/dashboard/queries';
import { AlertCircle } from 'lucide-react';
import { useEffect, useRef, useState } from 'react';
import mapboxgl from 'mapbox-gl';
import 'mapbox-gl/dist/mapbox-gl.css';

const MAPBOX_TOKEN = process.env.NEXT_PUBLIC_MAPBOX_ACCESS_TOKEN;

interface ZoneMapProps {
  data: ZoneIssueData[];
  loading?: boolean;
}

export default function ZoneMap({ data, loading = false }: ZoneMapProps) {
  const mapContainer = useRef<HTMLDivElement>(null);
  const map = useRef<mapboxgl.Map | null>(null);
  const [mapError, setMapError] = useState<string | null>(null);
  const [geoJsonData, setGeoJsonData] =
    useState<GeoJSONFeatureCollection | null>(null);
  const [selectedZone, setSelectedZone] = useState<string | null>(null);

  // Load GeoJSON on mount
  useEffect(() => {
    const loadGeoJson = async () => {
      const data = await loadMandaueGeoJSON();
      setGeoJsonData(data);
    };
    loadGeoJson();
  }, []);

  // Initialize map
  useEffect(() => {
    if (!mapContainer.current || !MAPBOX_TOKEN) {
      if (!MAPBOX_TOKEN) {
        setMapError('Mapbox token not configured');
      }
      return;
    }

    if (!geoJsonData) return;

    try {
      mapboxgl.accessToken = MAPBOX_TOKEN;

      map.current = new mapboxgl.Map({
        container: mapContainer.current,
        style: 'mapbox://styles/mapbox/light-v11',
        center: [123.93, 10.35],
        zoom: 11.5,
        pitch: 0,
        scrollZoom: false,
        dragPan: true,
        dragRotate: false,
        doubleClickZoom: false,
        touchZoomRotate: false,
        attributionControl: false,
      });

      map.current.on('load', () => {
        if (!map.current) return;

        // Add GeoJSON source
        map.current.addSource('barangay-source', {
          type: 'geojson',
          // eslint-disable-next-line @typescript-eslint/no-explicit-any
          data: geoJsonData as any,
          generateId: true,
        });

        // Add fill layer with enhanced visibility for low-count zones
        map.current.addLayer({
          id: 'barangay-fill',
          type: 'fill',
          source: 'barangay-source',
          paint: {
            'fill-color': [
              'interpolate',
              ['linear'],
              ['coalesce', ['feature-state', 'issueCount'], 0],
              0,
              'rgba(240, 240, 240, 0.3)',
              1,
              'rgba(191, 219, 254, 0.7)',
              3,
              'rgba(147, 197, 253, 0.75)',
              5,
              'rgba(96, 165, 250, 0.8)',
              10,
              'rgba(251, 146, 60, 0.85)',
              15,
              'rgba(249, 115, 22, 0.9)',
              20,
              'rgba(220, 38, 38, 0.95)',
            ],
            'fill-opacity': [
              'case',
              ['==', ['feature-state', 'issueCount'], 0],
              0.15,
              ['>=', ['feature-state', 'issueCount'], 1],
              0.85,
              0.15,
            ],
          },
        });

        // Add outline layer with emphasis on zones with issues
        map.current.addLayer({
          id: 'barangay-outline',
          type: 'line',
          source: 'barangay-source',
          paint: {
            'line-color': [
              'case',
              ['>=', ['feature-state', 'issueCount'], 10],
              'rgba(220, 38, 38, 0.9)',
              ['>=', ['feature-state', 'issueCount'], 5],
              'rgba(249, 115, 22, 0.8)',
              ['>=', ['feature-state', 'issueCount'], 1],
              'rgba(59, 130, 246, 0.7)',
              'rgba(100, 100, 100, 0.3)',
            ],
            'line-width': [
              'case',
              ['>=', ['feature-state', 'issueCount'], 10],
              3,
              ['>=', ['feature-state', 'issueCount'], 5],
              2.5,
              ['>=', ['feature-state', 'issueCount'], 1],
              2,
              1,
            ],
            'line-opacity': 1,
          },
        });

        // Update feature state with issue counts
        if (geoJsonData.features) {
          geoJsonData.features.forEach((feature, index) => {
            const barangayName = feature.properties?.name;
            const zoneData = data.find(
              (z) => z.zone.toLowerCase() === barangayName?.toLowerCase()
            );
            const issueCount = zoneData?.count || 0;

            // Use index as ID (generated by Mapbox due to generateId: true)
            map.current?.setFeatureState(
              { source: 'barangay-source', id: index },
              { issueCount }
            );
          });
        }
      });
    } catch (error) {
      console.error('Map error:', error);
      setMapError('Failed to initialize map');
    }

    return () => {
      map.current?.remove();
    };
  }, [geoJsonData, data, selectedZone]);

  // Loading state
  if (loading) {
    return (
      <div className="rounded-lg border border-[#ced1cd] bg-white p-6">
        <div className="grid grid-cols-1 items-stretch gap-6 md:grid-cols-3">
          <div className="md:col-span-2">
            <Skeleton className="h-[28rem] w-full rounded-lg md:h-[36rem]" />
          </div>
          <div className="h-[28rem] space-y-3 md:h-[36rem]">
            <Skeleton className="h-8 w-1/2" />
            <Skeleton className="h-6 w-full" />
            <Skeleton className="h-6 w-full" />
            <Skeleton className="h-6 w-full" />
          </div>
        </div>
      </div>
    );
  }

  if (!data || data.length === 0) {
    return (
      <div>
        <div className="flex h-48 items-center justify-center text-gray-500">
          <p>No zone data available</p>
        </div>
      </div>
    );
  }

  // Sort by count descending
  const sortedData = [...data].sort((a, b) => b.count - a.count);
  const totalIssues = sortedData.reduce((sum, z) => sum + z.count, 0) || 0;

  return (
    <div>
      <div className="grid grid-cols-1 items-stretch gap-6 md:grid-cols-3">
        {/* Map: left 2/3 */}
        <div className="md:col-span-2">
          {mapError ? (
            <div className="flex h-[28rem] items-center justify-center rounded-lg border border-red-200 bg-red-50 md:h-[36rem]">
              <div className="text-center">
                <AlertCircle className="mx-auto mb-2 h-12 w-12 text-red-600" />
                <p className="font-medium text-red-800">{mapError}</p>
                <p className="mt-1 text-sm text-red-600">
                  Please configure Mapbox token to enable map visualization
                </p>
              </div>
            </div>
          ) : (
            <div
              ref={mapContainer}
              className="h-[28rem] overflow-hidden rounded-lg border md:h-[36rem]"
            />
          )}
        </div>

        {/* Top zones: right 1/3 */}
        <aside className="flex h-[28rem] flex-col space-y-4 md:h-[36rem]">
          <div className="h-full overflow-auto rounded-md border bg-gray-50 p-3">
            <h4 className="mb-3 font-semibold text-gray-900">Top Zones</h4>
            <ul className="space-y-2">
              {sortedData.slice(0, 12).map((zone) => {
                const { bgColor, color } = getZoneColorByCount(zone.count);
                const isSelected = zone.zone === selectedZone;
                return (
                  <li key={zone.zone}>
                    <button
                      onClick={() =>
                        setSelectedZone(
                          zone.zone === selectedZone ? null : zone.zone
                        )
                      }
                      className={`flex w-full items-center justify-between gap-3 rounded-md p-2 text-left transition-colors hover:bg-gray-100 ${
                        isSelected ? 'ring-2 ring-blue-500 ring-offset-2' : ''
                      }`}
                    >
                      <div className="flex items-center gap-3">
                        <span
                          className={`inline-block h-3 w-3 rounded-full ${bgColor}`}
                        />
                        <span className="truncate text-sm font-medium">
                          {zone.zone}
                        </span>
                      </div>
                      <div className="text-right">
                        <div className={`text-lg font-semibold ${color}`}>
                          {zone.count}
                        </div>
                        <div className="text-xs text-gray-500">
                          {totalIssues
                            ? `${((zone.count / totalIssues) * 100).toFixed(0)}%`
                            : '0%'}
                        </div>
                      </div>
                    </button>
                  </li>
                );
              })}
            </ul>
          </div>
        </aside>
      </div>
    </div>
  );
}
