'use client';

import { Skeleton } from '@/components/ui/skeleton';
import {
  loadMandaueGeoJSON,
  type GeoJSONFeatureCollection,
} from '@/lib/dashboard/geojson';
import type { ZoneIssueData } from '@/lib/dashboard/queries';
import { AlertCircle } from 'lucide-react';
import { useEffect, useRef, useState } from 'react';
import mapboxgl from 'mapbox-gl';
import 'mapbox-gl/dist/mapbox-gl.css';

const MAPBOX_TOKEN = process.env.NEXT_PUBLIC_MAPBOX_ACCESS_TOKEN;

interface ZoneMapProps {
  data: ZoneIssueData[];
  loading?: boolean;
}

export default function ZoneMap({ data, loading = false }: ZoneMapProps) {
  const mapContainer = useRef<HTMLDivElement>(null);
  const map = useRef<mapboxgl.Map | null>(null);
  const [mapError, setMapError] = useState<string | null>(null);
  const [geoJsonData, setGeoJsonData] =
    useState<GeoJSONFeatureCollection | null>(null);
  const [selectedZone, setSelectedZone] = useState<string | null>(null);

  // Load GeoJSON on mount
  useEffect(() => {
    const loadGeoJson = async () => {
      const data = await loadMandaueGeoJSON();
      setGeoJsonData(data);
    };
    loadGeoJson();
  }, []);

  // Initialize map
  useEffect(() => {
    if (!mapContainer.current || !MAPBOX_TOKEN) {
      if (!MAPBOX_TOKEN) {
        setMapError('Mapbox token not configured');
      }
      return;
    }

    if (!geoJsonData) return;

    try {
      mapboxgl.accessToken = MAPBOX_TOKEN;

      map.current = new mapboxgl.Map({
        container: mapContainer.current,
        style: 'mapbox://styles/mapbox/outdoors-v12',
        center: [123.93, 10.35],
        zoom: 13,
        pitch: 0,
        scrollZoom: false,
        dragPan: true,
        dragRotate: false,
        doubleClickZoom: false,
        touchZoomRotate: false,
        attributionControl: false,
        maxBounds: [
          [123.75, 10.2],
          [124.15, 10.5],
        ],
      });

      map.current.on('load', () => {
        if (!map.current) return;

        // Add GeoJSON source
        map.current.addSource('barangay-source', {
          type: 'geojson',
          // eslint-disable-next-line @typescript-eslint/no-explicit-any
          data: geoJsonData as any,
          generateId: true,
        });

        // Add fill layer with enhanced visibility for low-count zones
        map.current.addLayer({
          id: 'barangay-fill',
          type: 'fill',
          source: 'barangay-source',
          paint: {
            'fill-color': [
              'interpolate',
              ['linear'],
              ['coalesce', ['feature-state', 'issueCount'], 0],
              0,
              'rgba(240, 240, 240, 0.15)',
              1,
              'rgba(191, 219, 254, 0.35)',
              3,
              'rgba(147, 197, 253, 0.4)',
              5,
              'rgba(96, 165, 250, 0.45)',
              10,
              'rgba(251, 146, 60, 0.5)',
              15,
              'rgba(249, 115, 22, 0.5)',
              20,
              'rgba(220, 38, 38, 0.5)',
            ],
            'fill-opacity': [
              'case',
              ['==', ['feature-state', 'issueCount'], 0],
              0.1,
              ['>=', ['feature-state', 'issueCount'], 1],
              0.5,
              0.1,
            ],
          },
        });

        // Add outline layer with emphasis on zones with issues
        map.current.addLayer({
          id: 'barangay-outline',
          type: 'line',
          source: 'barangay-source',
          paint: {
            'line-color': [
              'case',
              ['>=', ['feature-state', 'issueCount'], 10],
              'rgba(220, 38, 38, 0.5)',
              ['>=', ['feature-state', 'issueCount'], 5],
              'rgba(249, 115, 22, 0.4)',
              ['>=', ['feature-state', 'issueCount'], 1],
              'rgba(59, 130, 246, 0.35)',
              'rgba(100, 100, 100, 0.2)',
            ],
            'line-width': [
              'case',
              ['>=', ['feature-state', 'issueCount'], 10],
              1.5,
              ['>=', ['feature-state', 'issueCount'], 5],
              1.2,
              ['>=', ['feature-state', 'issueCount'], 1],
              1,
              0.5,
            ],
            'line-opacity': 0.7,
          },
        });

        // Update feature state with issue counts
        if (geoJsonData.features) {
          geoJsonData.features.forEach((feature, index) => {
            const barangayName = feature.properties?.name;
            const zoneData = data.find(
              (z) => z.zone.toLowerCase() === barangayName?.toLowerCase()
            );
            const issueCount = zoneData?.count || 0;

            // Use index as ID (generated by Mapbox due to generateId: true)
            map.current?.setFeatureState(
              { source: 'barangay-source', id: index },
              { issueCount }
            );
          });
        }
      });
    } catch (error) {
      console.error('Map error:', error);
      const errorMessage =
        error instanceof Error ? error.message : String(error);
      setMapError(`Failed to initialize map: ${errorMessage}`);
    }

    return () => {
      map.current?.remove();
    };
  }, [geoJsonData, data, selectedZone]);

  // Loading state
  if (loading) {
    return (
      <div className="grid grid-cols-1 items-stretch gap-6 md:grid-cols-6">
        <div className="md:col-span-4">
          <Skeleton className="h-[28rem] w-full rounded-lg md:h-[36rem]" />
        </div>
        <div className="h-[28rem] space-y-3 md:col-span-2 md:h-[36rem]">
          <Skeleton className="h-12 w-full rounded-lg" />
          <div className="flex-1 space-y-3 overflow-hidden">
            {[1, 2, 3, 4, 5].map((i) => (
              <Skeleton key={i} className="h-16 w-full rounded-lg" />
            ))}
          </div>
        </div>
      </div>
    );
  }

  if (!data || data.length === 0) {
    return (
      <div className="grid grid-cols-1 items-stretch gap-6 md:grid-cols-6">
        <div className="md:col-span-4">
          <div className="flex h-[28rem] items-center justify-center rounded-lg border border-yellow-200 bg-yellow-50 md:h-[36rem]">
            <div className="text-center">
              <AlertCircle className="mx-auto mb-2 h-12 w-12 text-yellow-600" />
              <p className="font-medium text-yellow-800">
                No zone data available
              </p>
            </div>
          </div>
        </div>
        <aside className="flex h-[28rem] flex-col md:col-span-2 md:h-[36rem]">
          <div className="rounded-lg border bg-gray-50 p-4">
            <p className="text-sm text-gray-600">No zones to display</p>
          </div>
        </aside>
      </div>
    );
  }

  // Sort by count descending
  const sortedData = [...data].sort((a, b) => b.count - a.count);
  const totalIssues = sortedData.reduce((sum, z) => sum + z.count, 0) || 0;

  // City information
  const cityName = 'Mandaue City, Philippines';
  // const landArea = '34.87 km²';

  // Helper function to get contribution box colors
  const getContributionColor = (percentage: number) => {
    if (percentage >= 80) return 'bg-red-600';
    if (percentage >= 30) return 'bg-blue-500';
    return 'bg-green-500';
  };

  // Helper function to create contribution boxes (like GitHub commits)
  const renderContributionBoxes = (percentage: number) => {
    const boxCount = 20; // Number of boxes in the bar
    const filledBoxes = Math.round((percentage / 100) * boxCount);

    return (
      <div className="flex w-full gap-1">
        {Array.from({ length: boxCount }).map((_, index) => (
          <div
            key={index}
            className={`aspect-square flex-1 border ${
              index < filledBoxes
                ? `${getContributionColor(percentage)} border-transparent`
                : 'border-gray-300 bg-gray-200'
            }`}
          />
        ))}
      </div>
    );
  };

  return (
    <div>
      <div className="grid grid-cols-1 items-stretch gap-6 md:grid-cols-6">
        {/* Map: left 4/6 */}
        <div className="md:col-span-4">
          {mapError ? (
            <div className="flex h-[28rem] items-center justify-center rounded-lg border border-red-200 bg-red-50 md:h-[36rem]">
              <div className="text-center">
                <AlertCircle className="mx-auto mb-2 h-12 w-12 text-red-600" />
                <p className="font-medium text-red-800">{mapError}</p>
                <p className="mt-1 text-sm text-red-600">
                  Please configure Mapbox token to enable map visualization
                </p>
              </div>
            </div>
          ) : (
            <div
              ref={mapContainer}
              className="h-[28rem] overflow-hidden rounded-lg border border-[#ced1cd] md:h-[36rem]"
            />
          )}
        </div>

        {/* Barangays: right 2/6 */}
        <aside className="flex h-[28rem] flex-col md:col-span-2 md:h-[36rem]">
          {/* Sticky Header */}
          <div className="sticky top-0 z-10 rounded-t-lg border border-[#dddbdc] bg-[#f9f7f8] px-5 py-3">
            {/* City Info and Total Issues in same row */}
            <div className="flex items-start justify-between gap-3">
              {/* City Info */}
              <div className="min-w-0 flex-1">
                <div className="flex flex-row justify-between">
                  <h3 className="truncate text-sm text-gray-900">{cityName}</h3>
                  <p className="text-muted-foreground text-sm">{totalIssues}</p>
                </div>
              </div>
            </div>
          </div>

          {/* Scrollable Zone List */}
          <div className="flex-1 overflow-auto rounded-b-lg border-x border-b bg-white px-4 pt-3 pb-5">
            <ul className="space-y-2">
              {sortedData.slice(0, 12).map((zone) => {
                const percentage = totalIssues
                  ? (zone.count / totalIssues) * 100
                  : 0;
                const isSelected = zone.zone === selectedZone;
                return (
                  <li key={zone.zone}>
                    <button
                      onClick={() =>
                        setSelectedZone(
                          zone.zone === selectedZone ? null : zone.zone
                        )
                      }
                      className={`flex w-full flex-col gap-2.5 rounded-md px-4 pt-2 pb-4 text-left transition-colors hover:bg-gray-100 ${
                        isSelected ? 'ring-1 ring-blue-500' : ''
                      }`}
                    >
                      <div className="flex min-w-0 items-center justify-between">
                        <span className="truncate text-sm font-medium">
                          {zone.zone}
                        </span>
                        <span className="ml-2 flex-shrink-0 text-xs font-semibold text-gray-700">
                          {zone.count}
                        </span>
                      </div>
                      <div className="w-full">
                        {renderContributionBoxes(percentage)}
                      </div>
                    </button>
                  </li>
                );
              })}
            </ul>
          </div>
        </aside>
      </div>
    </div>
  );
}
